[package]
org = "ballerinax"
name = "belgium.federal.clinical.core100"
version = "1.0.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "belgium_federal_clinical_core100"]

