[package]
org = "ballerinax"
name = "health.fhir.r4.aubase410"
version = "1.2.1"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "AUBase"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.aubase410"]
