[package]
org = "ballerinax"
name = "health.fhir.r4.aubase421"
version = "1.1.1"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "aubase421"]
export = ["health.fhir.r4.aubase421"]

